#!/bin/sh

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations -------------------------------#
multihead &
bspc config border_radius 7
bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.50

bspc config focused_border_color "$CYAN" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
# mouse action
#bspc config pointer_modifier mod1

#bspc config pointer_action1 move



#bspc config pointer_mod         mod4
#bspc config pointer_action1     move

## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > web
bspc rule -a firefox desktop='^1' follow=on focus=on

# 2 > terminal
bspc rule -a Alacritty desktop='^2' follow=on focus=on

# 3 > file
bspc rule -a Pcmanfm  desktop='^3' follow=on focus=on
bspc rule -a "microsoft teams - preview" desktop='^3' follow=off focus=off
bspc rule -a "Microsoft Teams - Preview" desktop='^3' follow=off focus=off
bspc rule -a "Steam" desktop='^6' follow=off focus=off

# 4 > office
bspc rule -a "Bitwarden" desktop='^0' follow=on focus=on
declare -a office=(Geany Gucharmap Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^9' follow=on focus=on; done

# 5 > media
bspc rule -a "discord" desktop='^5' follow=on focus=on

# 6 > settings
bspc rule -a GParted desktop='^6' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# 6 > games
bspc rula -a "Dota 2:dota2" desktop='^9'


# special rules
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a "Zathura" state=tiled focus=on follow=on

## Autostart -------------------------------#

# Kill if already running
killall -q sxhkd dunst

# Lauch notification daemon
dunst &

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Set wallpaper
setwallpaper

# Start bspwm scripts
multihead &
bspcomp &
bspbar &
bspshift &
bspmusic &
#pgrep bspswallow || bspswallow &
#wmname LG3D &
#exec "systemctl --user import-environment; systemctl --user start graphical-session.target"
